language: generic 
sudo: required
services:
  - docker

before_install:
  - docker run -e CI=true alexyoungz/react-test npm test

script:
  - docker run alexyoungz/react-test npm test -- --coverage

after_success:
  - docker build -t alexyoungz/multi-client ./client
  - docker build -t alexyoungz/multi-ngix ./ngix
  - docker build -t alexyoungz/multi-sever ./sever
  - docker build -t alexyoungz/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push alexyoungz/multi-client
  - docker push alexyoungz/multi-ngix
  - docker push alexyoungz/multi-sever
  - docker push alexyoungz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-655586358131
  bucket_path: docker-multi
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  